### ISSUE TITLE
app:testDevReleaseUnitTest does not pass

### ISSUE THREAD

**Issue by stuartsoft** [madebyatomicrobot/android-starter-project#23]
```
com.stuartsoft.foobar.SimpleRobolectricTest > classMethod FAILED
    java.lang.RuntimeException

3 tests completed, 1 failed
:app:testDevReleaseUnitTest FAILED

FAILURE: Build failed with an exception.
```

**Comment by stuartsoft** [comment]
Maybe try doing a fresh clone of the starter project and run `./gradlew build`
If the tests pass, then it's probably an issue with the renamePackage causing an issue with the test.

**Comment by stuartsoft** [comment]
I did a fresh clone of the starter project and simply ran `gradlew build` and the test did not pass. So it's likely not an issue with the `renamePackage.py`.

**Comment by patrickhammond** [comment]
I haven't been able to reproduce this yet.

Tried running `./gradlew continuousIntegration` both before and after a rename (first cleaning the project on the renamed project).  Both runs were successful.

**Comment by stuartsoft** [comment]
After further investigation, the problem seems to be isolated to the app:testDevReleaseUnitTest gradle task. I was able to validate that `gradlew continuousIntegration` was running fine so there should be no issue with running things on the build server, however simply running `gradlew build` will fail as a result of the testDevReleaseUnitTest task. My tests were conducted on a bone stock clone of this repo (didn't run renamepackage.py).

<img src="https://cloud.githubusercontent.com/assets/6208902/24087996/ccac776e-0cfb-11e7-9775-3443669fabb4.png" width="400px"/>

```
java.lang.RuntimeException: Could not load class: com.mycompany.myapp.app.RobolectricApplication
	at org.robolectric.annotation.Config$Implementation.parseClass(Config.java:191)
	at org.robolectric.annotation.Config$Implementation.parseApplication(Config.java:207)
	at org.robolectric.annotation.Config$Implementation.fromProperties(Config.java:180)
	at org.robolectric.RobolectricTestRunner.buildGlobalConfig(RobolectricTestRunner.java:361)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:317)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:162)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
